title:              Ciencia de datos
email:              dev-ahumada@gmail.com
description:        Tutoriales, consejos y trucos
author:             Luis Ahumada
baseurl:            ""
url:                "https://dev-ahumada.github.io"

# Social Profiles
twitter_username:   
github_username:    dev-ahumada
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
input: GFM
syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site